# action.yml
name: 'Get ACR ManagedId Login'
description: 'Get ACR ManagedId Login'
inputs:
  acr_uri:  
    description: 'Azure Container Registry URI'
    required: true
  client_id:  
    description: 'Client ID (in case of multiple managed identity)'
    required: false
  tenant_id:  
    description: 'Tenant ID'
    required: false
outputs:
  result:
    description: 'ACR token'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.acr_uri }}    
    - ${{ inputs.client_id }}
    - ${{ inputs.tenant_id }}