# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  acr-uri:  # id of input
    description: 'Acr URI'
    required: true
  tenant-id:  # id of input
    description: 'Tenant ID'
    required: true
outputs:
  token: # id of output
    description: 'Token from managed identity'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.acr-uri }}
    - ${{ inputs.tenant-id }}