# action.yml
name: 'Get ACR ManagedId Login'
description: 'Get ACR ManagedId Login'
inputs:
  acr_uri:  
    description: 'Azure Container Registry URI'
    required: true
  client_id:  
    description: 'Client ID (in case of multiple managed identity)'
    required: false
  tenant_id:  
    description: 'Tenant ID'
    required: false
outputs:
  token: # id of output
    description: 'Token from managed identity'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    - name: ACR_URI
      value: ${{ inputs.acr_uri }}