# action.yml
name: 'ACR Login'
description: 'ACR Login'
inputs:
  acr-uri:  # id of input
    description: 'Acr URI'
    required: true
  tenant-id:  # id of input
    description: 'Tenant ID'
    required: true
outputs:
  token: # id of output
    description: 'Token from managed identity'
runs:
  using: 'docker'
  image: 'Dockerfile'